
import { InputField, OutputField, Branches } from "./types/Schema";
import type { Lead } from "./types/Lead";
import { Node } from "./types/Node";
import {z} from "zod";

const node = {"name":"Book Slot","id":"youcanbookme_api_book_slot","descripition":"Books the chosen slot on the YouCanBookMe page. Creates a real confirmed booking. Pass the 'startsAt' value exactly as returned by getAvailableSlots. Fields marked COMPULSORY must be collected from the customer before calling.","inputSchema": {
    dealId: {
      name: "dealId",
      description: "OPTIONAL. CRM Deal ID to attach to the booking. → YCBM 'Deal ID' (DEAL_ID). Defaults to 327860506345 when not provided.",
      required: false,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.string()).parse(value); } catch { return value; } },
    },
    previousCustomer: {
      name: "previousCustomer",
      description: "OPTIONAL. → YCBM 'Previous Customer' (PREV_CUSTOMER). One of: 'Yes - At least one previous won deal', 'No - Past bids but no won deals', 'No History - No past deals/bids'.",
      required: false,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.any()).parse(value); } catch { return value; } },
    },
    referredBy: {
      name: "referredBy",
      description: "OPTIONAL. Name of the person who referred the customer. → YCBM 'Referred By:' (REFERRAL).",
      required: false,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.string()).parse(value); } catch { return value; } },
    },
    hospitalityNotes: {
      name: "hospitalityNotes",
      description: "OPTIONAL. Suggestions for what the estimator can bring (e.g. dog toy, sports swag). → YCBM 'Unreasonable Hospitality' (HOSPITALITY).",
      required: false,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.string()).parse(value); } catch { return value; } },
    },
    personalDetails: {
      name: "personalDetails",
      description: "OPTIONAL. Personal details captured during the call (interests, life events, etc.) for unreasonable-hospitality follow-up. → YCBM 'Personal Details' (PERSONAL_DETAILS).",
      required: false,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.string()).parse(value); } catch { return value; } },
    },
    schedulingIncentive: {
      name: "schedulingIncentive",
      description: "OPTIONAL. Customer's response to the scheduling incentive pre-close. → YCBM 'Scheduling Incentive' (SCHED_INCENTIVE). One of: 'Yes - Ready to Sign at Appt', 'No - Not Ready to Sign at Appt', 'Unsure - Timeline', 'Unsure - Budget', 'Unsure - Trust'.",
      required: false,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.any()).parse(value); } catch { return value; } },
    },
    secondHomeowner: {
      name: "secondHomeowner",
      description: "OPTIONAL. Whether a second homeowner will attend. → YCBM '2nd Homeowner' (SECOND_HOMEOWNER). One of: 'Yes - Will be at appt', 'No - Not available', 'N/A - No other decision maker'.",
      required: false,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.any()).parse(value); } catch { return value; } },
    },
    propertyOwner: {
      name: "propertyOwner",
      description: "OPTIONAL. Whether the caller is the property owner. → YCBM 'Property Owner' (PROPERTY_OWNER). 'Yes, I am' or 'No, I am not'.",
      required: false,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.any()).parse(value); } catch { return value; } },
    },
    revenueType: {
      name: "revenueType",
      description: "OPTIONAL. → YCBM 'Revenue Type' (REVENUE_TYPE). 'Painting' or 'Coating'.",
      required: false,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.any()).parse(value); } catch { return value; } },
    },
    divisionType: {
      name: "divisionType",
      description: "OPTIONAL. Division/Type tag. → YCBM 'Division/Type' (DIVISION_TYPE). One of: RES - EXT, RES - INT, RES - INT/EXT, FLR - EXT, FLR - INT, FLR - INT/EXT.",
      required: false,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.any()).parse(value); } catch { return value; } },
    },
    builtBefore1978: {
      name: "builtBefore1978",
      description: "OPTIONAL. Whether the home was built before 1978 (lead-paint screening). → YCBM 'House Built Before 1978?' (BUILT). 'Yes' or 'No'.",
      required: false,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.any()).parse(value); } catch { return value; } },
    },
    gateCode: {
      name: "gateCode",
      description: "OPTIONAL. Gate code or access instructions if the home is in a gated community. → YCBM 'Gate Code' (GATE_CODE).",
      required: false,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.string()).parse(value); } catch { return value; } },
    },
    companyName: {
      name: "companyName",
      description: "OPTIONAL. Customer company name. → YCBM 'Company Name' (COMPANY_NAME).",
      required: false,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.string()).parse(value); } catch { return value; } },
    },
    state: {
      name: "state",
      description: "OPTIONAL. Job site state. → YCBM 'Job Site State' (STATE). The booking page currently only accepts 'CA'. Defaults to 'CA' when not provided. Send it when you have the customer's state.",
      required: false,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.any()).parse(value); } catch { return value; } },
    },
    projectTimeline: {
      name: "projectTimeline",
      description: "COMPULSORY. Customer's timeline. → YCBM 'When are you looking to get this done?' (PROJECT_TIMELINE). One of: ASAP, Within the next 2 weeks, Sometime in the next month, Sometime this year, Just getting ideas and budget.",
      required: true,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.any()).parse(value); } catch { return value; } },
    },
    projectType: {
      name: "projectType",
      description: "COMPULSORY. One or more project types (multi-select). → YCBM 'Project Type' (PROJECT_TYPE). FLR = Concrete Coating, EXTP = Exterior Painting, INTP = Interior Painting. Example: [\"INTP\", \"EXTP\"].",
      required: true,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.array(z.any())).parse(value); } catch { return []; } },
    },
    description: {
      name: "description",
      description: "COMPULSORY. Free-form project description capturing the painting / coating qualification answers (scope, surfaces, problem areas, etc.). → YCBM 'Please describe your project' (DESCRIPTION).",
      required: true,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.string()).parse(value); } catch { return value; } },
    },
    zip: {
      name: "zip",
      description: "COMPULSORY. Job site zip code. → YCBM 'Job Site Zip Code' (ZIP).",
      required: true,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.string()).parse(value); } catch { return value; } },
    },
    city: {
      name: "city",
      description: "COMPULSORY. Job site city. → YCBM 'Job Site City' (CITY).",
      required: true,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.string()).parse(value); } catch { return value; } },
    },
    address: {
      name: "address",
      description: "COMPULSORY. Job site street address. → YCBM 'Job Site Address' (ADDRESS).",
      required: true,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.string()).parse(value); } catch { return value; } },
    },
    source: {
      name: "source",
      description: "COMPULSORY. How the customer heard about us. → YCBM 'How did you hear about us?' (SOURCE). One of: Brand, Online, Social Media, Direct Mail, Email / Text, Referral, Repeat Client, Biz Dev, Other.",
      required: true,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.any()).parse(value); } catch { return value; } },
    },
    phone: {
      name: "phone",
      description: "COMPULSORY. Customer mobile phone number (validated as mobile by YCBM). → YCBM 'Phone' (PHONE).",
      required: true,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.string()).parse(value); } catch { return value; } },
    },
    email: {
      name: "email",
      description: "COMPULSORY. Customer email address (validated as email by YCBM). → YCBM 'Email' (EMAIL).",
      required: true,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.string()).parse(value); } catch { return value; } },
    },
    lastName: {
      name: "lastName",
      description: "COMPULSORY. Customer last name. → YCBM 'Last Name' (LNAME).",
      required: true,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.string()).parse(value); } catch { return value; } },
    },
    firstName: {
      name: "firstName",
      description: "COMPULSORY. Customer first name. → YCBM 'First Name' (FNAME).",
      required: true,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.string()).parse(value); } catch { return value; } },
    },
    teamMemberId: {
      name: "teamMemberId",
      description: "COMPULSORY. The teamMemberId from the chosen slot, exactly as returned by getAvailableSlots. The booking will be made against this estimator.",
      required: true,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.string()).parse(value); } catch { return value; } },
    },
    startsAt: {
      name: "startsAt",
      description: "COMPULSORY. The startsAt token of the chosen slot, exactly as returned by getAvailableSlots (millisecond unix timestamp as string).",
      required: true,
      validationSchema: /.*/,
      errorMessage: "",
      input: { type: "text" },
      parse: (value: string) => { try { return (z.string()).parse(value); } catch { return value; } },
    },
  },"outputSchema": {
    result: {
      name: "Result",
      description: "Output of tool Book Slot from API YouCanBookMe API",
      example: "",
      validator: (value: any) => true,
    },
  },"groups":["YouCanBookMe API","Book Slot"],"branches":{"success":{"id":"success","name":"Success","description":"Successful execution"}},"isTriggerNode":false,"cost":0} as Node;

export { node as "youcanbookme_api_book_slot" };
